### ISSUE TITLE
First Commit needed

### ISSUE THREAD

**Issue by ocarriles** [RestComm/sbc#1]
Preparing repository for first commit

**Comment by ocarriles** [comment]
Ready

**Comment by deruelle** [comment]
@ocarriles I merged the work and will use this as placeholder for comments

**Comment by deruelle** [comment]
@ocarriles 

1. Let's remove .settings from the root directory
2. Let's remove build/classes from the root directory
3. Let's remove target from the root directory
4. Let's rename and move sbc root directory to src/main/webapp to follow maven conventions

**Comment by ocarriles** [comment]
@deruelle

removed .settings from the root directory
removed build/classes from the root directory
removed target from the root directory
renamed and moved sbc root directory to its own packages to follow maven conventions

**Comment by ocarriles** [comment]
sbc.* renamed to * at root dir
uml dir moved to doc dir
Mutable/Immutable Messages and DPI abstraction API now included in chain-subsystem
