### ISSUE TITLE
VPN connectivity support

### ISSUE THREAD

**Issue by marca56** [RestComm/sbc#103]

**Comment by ocarriles** [comment]
@marca56 Do you mean, for instance, to be an OpenVPN terminator?

**Comment by marca56** [comment]
Yes; @ocarriles, sorry for not introducing myself and explaining what I did here with all the stories in the sprint backlog. I will send you a separate email and we can setup an intro call.

**Comment by ocarriles** [comment]
merge #92 duplicated
