### ISSUE TITLE
Use Guarded logging 

### ISSUE THREAD

**Issue by deruelle** [RestComm/sbc#11]
for DEBUG, INFO, TRACE, ...

**Comment by ocarriles** [comment]
Due to #24, a lot of paranoid logging stuff is in place.
This will be removed later.
Best practices will be applied for those that will stay at production stage .

**Comment by deruelle** [comment]
ok leaving that one open, so we don't forget to cleanup. We all know what temporary code means. We can still see it in https://github.com/chrislgarry/Apollo-11 :D
