### ISSUE TITLE
Use HashMap or ConcurrentHashmap or javolution map instead of Hashtable

### ISSUE THREAD

**Issue by deruelle** [RestComm/sbc#12]
as in title

**Comment by ocarriles** [comment]
Some Hashtables converted to HashMaps.
The work is yet in progress. Refactoring will be done

**Comment by deruelle** [comment]
I still see some Hashtable after the Pull request merge from https://github.com/RestComm/sbc/pull/23.

Let's create separate PR for this issue from now on
