### ISSUE TITLE
Spike: Review Oscar's current documentation 

### ISSUE THREAD

**Issue by marca56** [RestComm/sbc#127]
[https://app.zenhub.com/files/55970222/ceea1210-2860-43ec-ba3c-14f9fda9330f/download](https://app.zenhub.com/files/55970222/ceea1210-2860-43ec-ba3c-14f9fda9330f/download)[https://app.zenhub.com/files/55970222/eef12f96-d832-4aba-bb74-4d869ab6e27a/download](https://app.zenhub.com/files/55970222/eef12f96-d832-4aba-bb74-4d869ab6e27a/download)

**Comment by ocarriles** [comment]
@marca56  Any comment?
