### ISSUE TITLE
SIPMutableMessage : message.getProperty("content"); is used everywhere

### ISSUE THREAD

**Issue by deruelle** [RestComm/sbc#17]
Check if it would make sense to get rid of the Properties and just encapsulate the message or at least hide the "content" and just do a get to get the message as the Properties doesn't seem to be use in any other way than to access the "content" property anyway.

**Comment by ocarriles** [comment]
Removed Property instance and wrap Message content via getter and setter
fix #17 @deruelle

**Comment by deruelle** [comment]
Thanks @ocarriles. If done with commits please do a pull request

**Comment by ocarriles** [comment]
Done
