### ISSUE TITLE
Implement Topology Hiding

### ISSUE THREAD

**Issue by deruelle** [RestComm/sbc#18]

**Comment by ocarriles** [comment]
Partially implemented

**Comment by ocarriles** [comment]
DMZ cannot sniff any internal data
some traces still remain at MZ side for debugging purposes

**Comment by ocarriles** [comment]
Must close as topology hiding is an intrinsic design topic, not a feature.
@deruelle

**Comment by ocarriles** [comment]
closed on no comments
