### ISSUE TITLE
WebRTC Gateway capabilities

### ISSUE THREAD

**Issue by deruelle** [RestComm/sbc#20]
Allow to convert SIP Over Websockets (and Secure) to UDP, TCP or TLS. Handling of Media will probably require Media Server integration which could be left out for the BETA release

**Comment by ocarriles** [comment]
Agreed. Media handling left to beta release. SIP/SDP signaling is a MUST for ALPHA releasing.

**Comment by dgutzeit** [comment]
DTLS offloading is another must feature, when talking about WebRTC gateway capabilities

**Comment by deruelle** [comment]
@dgutzeit agreed. We plan to have a configuration flag potentially for that. The work on media is being done as part of https://github.com/RestComm/sbc/issues/41

**Comment by ocarriles** [comment]
Dtls handshake is now working and decoding/encoding media stream is also possible.
As jean told you, this feature will be available via SBC.xml config flag.

**Comment by ocarriles** [comment]
done
@deruelle  please close
