### ISSUE TITLE
Implement REST API for provisioning

### ISSUE THREAD

**Issue by deruelle** [RestComm/sbc#21]

**Comment by ocarriles** [comment]
@deruelle  do you mean PUT services to configure the sbc box from REST?

**Comment by ocarriles** [comment]
REST stuff in place, look at RESTLocationService

**Comment by deruelle** [comment]
Thanks @ocarriles .

I'm thinking we should probably have a way to break it down by pages as if there is a lot of registered clients the content will be huge and take a lot of time to reply. Shall we create a separate issue for that and mark that one closed ?

**Comment by ocarriles** [comment]
Yes, I think so
Thanks @deruelle
