### ISSUE TITLE
Break down REST API for LocationService in multiple APIs

### ISSUE THREAD

**Issue by deruelle** [RestComm/sbc#28]

**Comment by ocarriles** [comment]
@deruelle Does make sense to do a full CRUD api?, just read-only implemented

**Comment by deruelle** [comment]
I think READ only operations are enough for now. I don't see the need for Create Read and Update. Maybe Delete could be useful for cleanup if some registrations are not cleaned up properly somehow

**Comment by ocarriles** [comment]
@deruelle LocationService renamed to LocationsEndpoint

**Comment by ocarriles** [comment]
@deruelle just done, any other requirement for this issue to remain open?

**Comment by deruelle** [comment]
> just done

Did you do a new pull request or commit on that ?

**Comment by ocarriles** [comment]
@deruelle 
Location data is now based on AoR (bob@sbc.domain)
As a multihome environment, issues still arises when same user try to register to different prospect domains (f.i. bob@sbc.domain.1). 
Please comment.

**Comment by deruelle** [comment]
@ocarriles can you describe exactly and potentially with a call flow the issue that still arise ? I'm not sure I got the sbc.domain.1

**Comment by ocarriles** [comment]
@deruelle 
Remaining issue is not related to the call flow but to the Location database.

a) SBC offers 2 public services at sbc.domain:5060/UDP and sbc1.domain:5060/TCP
b) user bob has a desktop phone that registers to sbc.domain;expires=3600 (bob@sbc.domain)
c) user bob has a softphone that registers to sbc1.domain;expires=3600 (bob@sbc1.domain)
d) bob@sbc1.domain rewrites backend registration 
e) bob@sbc.domain will keep its own local registration state alive for the next hour.
f) bob@sbc1.domain can make and receive calls
g) bob@sbc.domain cannot but already registered
h) Locations.size() returns 2

Am I wrong?

**Comment by deruelle** [comment]
What do you mean by "offers 2 public services at sbc.domain:5060/UDP and sbc1.domain:5060/TCP" ?

shouldn't it be  sbc.domain has 2 interfaces 5060/UDP and 5060/TCP ?

if you want to say that 2 devices can register to the same domain and use the same AoR then yes it's possible read https://www.ietf.org/rfc/rfc3261.txt section registrations. The registrar/location database will have 1 AoR and 2 Locations with the IP, port and transport of each device.

**Comment by ocarriles** [comment]
@deruelle 
You are right.
think I misunderstood AoR concept.
