### ISSUE TITLE
REST API for IP Filtering Provisioning

### ISSUE THREAD

**Issue by deruelle** [RestComm/sbc#29]
Allow to provision blacklisting and whitelisting of IPs manually

**Comment by ocarriles** [comment]
White/Black listing IP block /unblock will be managed by sbc.
Although IP layer baning rules best fit with underlaying IP firewalling stuff.
This task will delegate this role to the the firewall backoffice,

**Comment by deruelle** [comment]
we need to add unit tests

**Comment by ocarriles** [comment]
@deruelle 
please close
