### ISSUE TITLE
REST API - Interfaces (NetworkPoints)

### ISSUE THREAD

**Issue by ocarriles** [RestComm/sbc#34]
Tag autodetected NIC interfaces to be used as MZ/DMZ

**Comment by deruelle** [comment]
we call to a script to actually delegate the Firewall whitelisting or blacklisting (bab026b#diff-fa154f0f4c5f4e8efac48543ba57bb19R20), but no default script is present. We need to add some. Ideally one for AWS and one for regular linux ubuntu server box.

**Comment by ocarriles** [comment]
@deruelle Please relink comment to issue #29

**Comment by ocarriles** [comment]
@deruelle 
script commited at c63bb8e

**Comment by ocarriles** [comment]
@deruelle 
please close
